# Site Settings
title: Start Jekyll
email: satyakalyanam@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/startjekyll"
url: "http://satyakalyanam.github.io"
twitter_username: satyakalyanam
github_username:  satyakalyanam
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM